part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Icon tokens for the generated theme.
FIcons _icons() => FIcons(
  arrowLeft: const FIcon(FPhosphorBoldIcons.arrowLeft),
  calendar: const FIcon(FPhosphorBoldIcons.calendar),
  check: const FIcon(FPhosphorBoldIcons.check),
  chevronDown: const FIcon(FPhosphorBoldIcons.caretDown),
  chevronLeft: const FIcon(FPhosphorBoldIcons.caretLeft),
  chevronRight: const FIcon(FPhosphorBoldIcons.caretRight),
  chevronUp: const FIcon(FPhosphorBoldIcons.caretUp),
  chevronsUpDown: const FIcon(FPhosphorBoldIcons.caretUpDown),
  circleAlert: const FIcon(FPhosphorBoldIcons.warningCircle),
  clock4: const FIcon(FPhosphorBoldIcons.clock),
  ellipsis: const FIcon(FPhosphorBoldIcons.dotsThree),
  error: const FIcon(FPhosphorBoldIcons.warningCircle),
  eye: const FIcon(FPhosphorBoldIcons.eye),
  eyeClosed: const FIcon(FPhosphorBoldIcons.eyeClosed),
  gripHorizontal: const FIcon(FPhosphorBoldIcons.arrowsHorizontal),
  gripVertical: const FIcon(FPhosphorBoldIcons.arrowsVertical),
  loader: const FIcon(FPhosphorBoldIcons.spinnerGap),
  loaderCircle: const FIcon(FPhosphorBoldIcons.spinner),
  loaderPinwheel: const FIcon(FPhosphorBoldIcons.spinnerBall),
  search: const FIcon(FPhosphorBoldIcons.magnifyingGlass),
  userRound: const FIcon(FPhosphorBoldIcons.userCircle),
  x: const FIcon(FPhosphorBoldIcons.x),
);
