import 'package:dart_jellyfin/dart_jellyfin.dart';

extension JFItemCopy on JellyfinItem {
  JellyfinItem copyWith({JellyfinUserData? userData}) {
    return JellyfinItem(
      id: id,
      name: name,
      albumArtists: albumArtists,
      artists: artists,
      artistItems: artistItems,
      mediaSources: mediaSources,
      mediaStreams: mediaStreams,
      isFolder: isFolder,
      hasLyrics: hasLyrics,
      genres: genres,
      tags: tags,
      imageTags: imageTags,
      backdropImageTags: backdropImageTags,
      imageBlurHashes: imageBlurHashes,
      raw: raw,
      overview: overview,
      type: type,
      premiereDate: premiereDate,
      userData: userData ?? this.userData,
      productionYear: productionYear,
      runTimeTicks: runTimeTicks,
      album: album,
      albumArtist: albumArtist,
      albumId: albumId,
      albumPrimaryImageTag: albumPrimaryImageTag,
      childCount: childCount,
      collectionType: collectionType,
      container: container,
      dateCreated: dateCreated,
      height: height,
      indexNumber: indexNumber,
      mediaType: mediaType,
      originalTitle: originalTitle,
      parentId: parentId,
      parentIndexNumber: parentIndexNumber,
      primaryImageAspectRatio: primaryImageAspectRatio,
      seasonId: seasonId,
      seasonName: seasonName,
      seriesId: seriesId,
      seriesName: seriesName,
      sortName: sortName,
      width: width,
    );
  }
}
